# Generated by Django 5.1.1 on 2024-10-01 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyvalue',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='companyvalue',
            name='description_uz',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='companyvalue',
            name='title_ru',
            field=models.CharField(max_length=150, null=True, unique=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='companyvalue',
            name='title_uz',
            field=models.CharField(max_length=150, null=True, unique=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_ru',
            field=models.TextField(null=True, verbose_name='Ответ'),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_uz',
            field=models.TextField(null=True, verbose_name='Ответ'),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Вопрос'),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_uz',
            field=models.CharField(max_length=150, null=True, verbose_name='Вопрос'),
        ),
        migrations.AddField(
            model_name='news',
            name='full_description_ru',
            field=models.TextField(null=True, verbose_name='Полное описание'),
        ),
        migrations.AddField(
            model_name='news',
            name='full_description_uz',
            field=models.TextField(null=True, verbose_name='Полное описание'),
        ),
        migrations.AddField(
            model_name='news',
            name='short_description_ru',
            field=models.TextField(null=True, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='news',
            name='short_description_uz',
            field=models.TextField(null=True, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_uz',
            field=models.CharField(max_length=150, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='pointofsale',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Уточнение'),
        ),
        migrations.AddField(
            model_name='pointofsale',
            name='description_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Уточнение'),
        ),
        migrations.AddField(
            model_name='product',
            name='full_description_ru',
            field=models.TextField(null=True, verbose_name='Полное описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='full_description_uz',
            field=models.TextField(null=True, verbose_name='Полное описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_ru',
            field=models.CharField(max_length=150, null=True, unique=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_uz',
            field=models.CharField(max_length=150, null=True, unique=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description_ru',
            field=models.TextField(null=True, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description_uz',
            field=models.TextField(null=True, verbose_name='Краткое описание'),
        ),
    ]
